project_id = "bqfqznjwxcczhjwzdmch"

[functions.suggest-items]
verify_jwt = false

[functions.scan-image]
verify_jwt = false

[functions.national-average]
verify_jwt = false

[functions.smart-price-lookup]
verify_jwt = false

[functions.import-chain-prices]
verify_jwt = false